### ISSUE TITLE
Broken Resource Link

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-big-data-introduction#2]
## Link to Canvas

https://my.learn.co/courses/541/pages/introduction-to-big-data

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```
- [Introduction to Big Data](https://www.ntnu.no/iie/fag/big/lessons/lesson2.pdf) - A paper discussing the basics of big data
```

### Concern

URL returns a 404

**Comment by bpurdy-ds** [comment]
Resolved by
https://github.com/learn-co-curriculum/dsc-big-data-introduction/commit/38732adc91d3b531329db200162885cc49243b3d
